name: banking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.2
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
